/**
 * soil_model.h  --  VayuMitti Node B TinyML Soil Health Classifier
 * Auto-generated by m2cgen from scikit-learn DecisionTreeClassifier.
 * DO NOT EDIT manually. Re-run soil_health_model.ipynb to regenerate.
 *
 * Features (input array order):
 *   input[0] = pH               (3.0 - 11.0)
 *   input[1] = EC mS/cm         (0.01 - 6.0)
 *   input[2] = moisture %       (2.0 - 95.0)
 *   input[3] = temperature degC (0.0 - 55.0)
 *
 * Usage:
 *   #include "soil_model.h"
 *   double inp[] = { pH_val, ec_val, mois_val, temp_val };
 *   int cls = soil_predict(inp);  // 0=GOOD 1=ACIDIC 2=DRY 3=SALINE
 *   Serial.println(SOIL_CLASS_NAMES[cls]);
 */
#pragma once
#ifdef __cplusplus
extern "C" {
#endif

#define SOIL_CLASS_GOOD      0
#define SOIL_CLASS_ACIDIC    1
#define SOIL_CLASS_DRY       2
#define SOIL_CLASS_SALINE    3
#define SOIL_N_CLASSES       4

static const char* SOIL_CLASS_NAMES[4] = {
    "GOOD", "ACIDIC", "DRY_STRESSED", "SALINE_ALKALINE"
};

#include <string.h>
void score(double * input, double * output) {
    double var0[4];
    if (input[1] <= 1.398841142654419) {
        if (input[2] <= 22.61271381378174) {
            if (input[2] <= 20.774324417114258) {
                if (input[0] <= 5.59992527961731) {
                    memcpy(var0, (double[]){0.0, 0.0, 1.0, 0.0}, 4 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){0.0, 0.0, 1.0, 0.0}, 4 * sizeof(double));
                }
            } else {
                memcpy(var0, (double[]){0.0, 0.08695652173913043, 0.9130434782608695, 0.0}, 4 * sizeof(double));
            }
        } else {
            if (input[0] <= 5.71689510345459) {
                memcpy(var0, (double[]){0.0, 1.0, 0.0, 0.0}, 4 * sizeof(double));
            } else {
                if (input[2] <= 34.28822708129883) {
                    memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0}, 4 * sizeof(double));
                } else {
                    memcpy(var0, (double[]){1.0, 0.0, 0.0, 0.0}, 4 * sizeof(double));
                }
            }
        }
    } else {
        if (input[1] <= 1.6228070855140686) {
            memcpy(var0, (double[]){0.0, 0.0, 0.0, 1.0}, 4 * sizeof(double));
        } else {
            memcpy(var0, (double[]){0.0, 0.0, 0.0, 1.0}, 4 * sizeof(double));
        }
    }
    memcpy(output, var0, 4 * sizeof(double));
}


/* Returns integer class 0-3 directly */
static inline int soil_predict(double* input) {
    double output[4];
    score(input, output);
    int best = 0;
    for (int i = 1; i < 4; i++) {
        if (output[i] > output[best]) best = i;
    }
    return best;
}

#ifdef __cplusplus
}
#endif
